# Green Favoritism: Birth Regions, Nightlights, and Industrial Pollution

**Research question:** Do political leaders channel clean economic development to their birth regions while directing pollution-intensive industry elsewhere?

**Hypothesis (Green Favoritism):**
$$\hat\beta^{\text{lights}} > 0 \quad \text{and} \quad \hat\beta^{\text{NO}_2} \leq 0$$

Birth regions see rising nighttime lights (economic activity) but **not** rising NO₂ (industrial pollution) — i.e., a decoupling of growth from pollution in politically favored districts.

**Data:**
- Political leaders: PLAD (Bomprezzi et al., 2025) — ADM2 birth district coding
- Nightlights: Harmonized DMSP-OLS / VIIRS (Li et al., 2020), 2005–2019
- NO₂: ACAG surface NO₂ estimates (Cooper et al., 2022), 2005–2019
- Admin boundaries: GADM v4.1 ADM2 (built by `replication.ipynb`)

> **Prerequisite:** Run `replication.ipynb` first to build the ADM2 boundary cache (`data/gadm/gadm41_adm2.gpkg`).

In [1]:
import sys
import warnings
from pathlib import Path

import numpy as np
import pandas as pd
import geopandas as gpd
from rasterstats import zonal_stats
from linearmodels.panel import PanelOLS

warnings.filterwarnings("ignore")

ROOT      = Path("..")  # project root
DATA      = ROOT / "data"
NTL_DIR   = DATA / "nightlights"
PLAD_PATH = DATA / "political leaders" / "PLAD_April_2024.dta"
SCRIPTS   = (ROOT / "scripts").resolve()
if str(SCRIPTS) not in sys.path:
    sys.path.append(str(SCRIPTS))

from gid_utils import valid_gid_mask

# Proposal-aligned ACAG window
ANALYSIS_YEARS = range(2005, 2020)

## 1. Load shared boundary data

In [2]:
GADM_DIR   = DATA / "gadm"
ADM2_CACHE = GADM_DIR / "gadm41_adm2.gpkg"

assert ADM2_CACHE.exists(), (
    f"ADM2 boundary cache not found at {ADM2_CACHE}.\n"
    "Run replication.ipynb first to build it."
)

adm2 = gpd.read_file(ADM2_CACHE)
adm2 = adm2.loc[valid_gid_mask(adm2["GID_2"])].copy()
print(f"Loaded {len(adm2):,} ADM2 regions")
adm2.head(2)

Loaded 47,984 ADM2 regions

,GID_0,GID_1,GID_2,NAME_0,NAME_1,NAME_2,geometry
2,AFG,AFG.1_1,AFG.1.10_1,Afghanistan,Badakhshan,Shahri Buzurg,"MULTIPOLYGON (((70.32571 37.46014, 70.3063 37...."
3,AFG,AFG.1_1,AFG.1.11_1,Afghanistan,Badakhshan,Shighnan,"MULTIPOLYGON (((71.31807 37.24994, 71.30699 37..."

<cell_type>markdown</cell_type>## 2. Build PLAD treatment variables (2005–2019)

Same pipeline as `replication.ipynb`, but the spell expansion covers the ACAG analysis window (2005–2019).

In [4]:
plad = pd.read_stata(PLAD_PATH)
plad = plad[plad["foreign_leader"] == "0"].copy()

# Use gid_2 (ADM2 birth district) if available; fall back to gid_1
BIRTH_GID = "gid_2" if "gid_2" in plad.columns else "gid_1"
plad = plad.loc[valid_gid_mask(plad[BIRTH_GID])].copy()
plad["startyear"] = plad["startyear"].astype(int)
plad["endyear"]   = plad["endyear"].astype(int)
plad = plad[plad["archigos_id"].str.strip() != "."].copy()
plad = plad.sort_values(["gid_0", "startyear"]).reset_index(drop=True)

print(f"Using birth region column: {BIRTH_GID}")
print(f"Leaders: {len(plad)}  |  countries: {plad['country'].nunique()}")

Using birth region column: gid_2
Leaders: 820  |  countries: 151

In [5]:
# Fix transition-year overlap (same as replication.ipynb)
plad_fixed = plad.copy().reset_index(drop=True)
for gid_0, group in plad_fixed.groupby("gid_0"):
    idxs = group.index.tolist()
    for i in range(len(idxs) - 1):
        curr, nxt = idxs[i], idxs[i + 1]
        if plad_fixed.loc[curr, "endyear"] >= plad_fixed.loc[nxt, "startyear"]:
            plad_fixed.loc[curr, "endyear"] = plad_fixed.loc[nxt, "startyear"] - 1

# Expand spells into birth-district × year rows for ANALYSIS_YEARS
YEAR_MIN, YEAR_MAX = min(ANALYSIS_YEARS), max(ANALYSIS_YEARS)
rows = []
for idx, row in plad_fixed.iterrows():
    for y in range(max(int(row["startyear"]), YEAR_MIN),
                   min(int(row["endyear"]),   YEAR_MAX) + 1):
        rows.append({"GID_2": row[BIRTH_GID], "GID_0": row["gid_0"],
                     "year": y, "spell_id": idx})

leader_years = pd.DataFrame(rows)
leader_years = leader_years.loc[valid_gid_mask(leader_years["GID_2"])].copy()
leader_years = leader_years.drop_duplicates(subset=["GID_2", "year"])
leader_years["birth_region_leader"] = 1

spell_map = (leader_years[["GID_0", "year", "spell_id"]]
             .drop_duplicates(subset=["GID_0", "year"]))

print(f"Birth-district × year obs: {len(leader_years)}")
print(f"Unique leader spells:       {spell_map['spell_id'].nunique()}")
print(f"Year range in treatment:    {leader_years['year'].min()}–{leader_years['year'].max()}")

Birth-district × year obs: 1926
Unique leader spells:       368
Year range in treatment:    2005–2019

<cell_type>markdown</cell_type>## 3. Nightlights panel (harmonized DMSP-OLS / VIIRS, 2005–2019)

Use the harmonized Li et al. (2020) rasters in `data/nightlights/`:
- `Harmonized_DN_NTL_{year}_calDMSP.tif` for 2005–2013
- `Harmonized_DN_NTL_{year}_simVIIRS.tif` for 2014–2019

In [6]:
NTL_CACHE = DATA / "nightlights_adm2_green_favoritism_panel.parquet"


def raster_path(year):
    if year <= 2013:
        return NTL_DIR / f"Harmonized_DN_NTL_{year}_calDMSP.tif"
    return NTL_DIR / f"Harmonized_DN_NTL_{year}_simVIIRS.tif"


# Invalidate cache if it doesn't cover ANALYSIS_YEARS
def _cache_years_match(path, years):
    if not path.exists():
        return False
    cached = set(pd.read_parquet(path, columns=["year"])["year"].unique())
    return set(years).issubset(cached)


if _cache_years_match(NTL_CACHE, ANALYSIS_YEARS):
    print(f"Loading cached nightlights panel from {NTL_CACHE}")
    ntl_panel = pd.read_parquet(NTL_CACHE)
else:
    if NTL_CACHE.exists():
        print("Cache year range mismatch — rebuilding nightlights panel...")

    frames = []

    dmsp_cache = DATA / "nightlights_adm2_panel.parquet"
    if dmsp_cache.exists():
        dmsp = pd.read_parquet(dmsp_cache)
        dmsp = dmsp.loc[valid_gid_mask(dmsp["GID_2"])].copy()
        dmsp = dmsp[dmsp["year"].between(2005, 2013)].copy()
        if not dmsp.empty:
            print(f"Loading 2005–2013 from existing cache: {dmsp_cache}")
            frames.append(dmsp)

    viirs_cache = DATA / "nightlights_adm2_viirs_panel.parquet"
    if viirs_cache.exists():
        viirs = pd.read_parquet(viirs_cache)
        viirs = viirs.loc[valid_gid_mask(viirs["GID_2"])].copy()
        viirs = viirs[viirs["year"].between(2018, 2019)].copy()
        if not viirs.empty:
            print(f"Loading 2018–2019 from existing cache: {viirs_cache}")
            frames.append(viirs)

    missing_years = [
        year for year in ANALYSIS_YEARS
        if year not in {frame_year for frame in frames for frame_year in frame["year"].unique()}
    ]

    for year in missing_years:
        rpath = raster_path(year)
        assert rpath.exists(), f"Nightlights raster not found: {rpath}"
        print(f"  Processing {year} ({rpath.name})...", end=" ", flush=True)
        stats = zonal_stats(adm2.geometry, str(rpath), stats=["mean"], nodata=0)
        frames.append(pd.DataFrame({
            "GID_2":    adm2["GID_2"].values,
            "GID_1":    adm2["GID_1"].values,
            "GID_0":    adm2["GID_0"].values,
            "year":     year,
            "ntl_mean": [s["mean"] for s in stats],
        }))
        print("done")

    ntl_panel = pd.concat(frames, ignore_index=True)
    ntl_panel = ntl_panel[ntl_panel["year"].isin(ANALYSIS_YEARS)].copy()
    ntl_panel = ntl_panel.loc[valid_gid_mask(ntl_panel["GID_2"])].copy()
    ntl_panel.to_parquet(NTL_CACHE)
    print(f"\nSaved nightlights panel to {NTL_CACHE}")

ntl_panel = ntl_panel.loc[valid_gid_mask(ntl_panel["GID_2"])].copy()

print(f"Nightlights panel: {len(ntl_panel):,} obs | "
      f"{ntl_panel['GID_2'].nunique():,} regions | "
      f"years: {sorted(ntl_panel['year'].unique())}")

Loading cached nightlights panel from ../data/nightlights_adm2_green_favoritism_panel.parquet
Nightlights panel: 719,760 obs | 47,984 regions | years: [np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019)]

<cell_type>markdown</cell_type>## 4. Load ACAG NO₂ panel (2005–2019)

The proposal uses the ACAG surface NO₂ product (Cooper et al., 2022). Build it once with `scripts/build_acag_no2_panel.py`, then load the cached ADM2 panel here.

In [7]:
NO2_PANEL_CACHE = DATA / "no2_adm2_acag_panel.parquet"

assert NO2_PANEL_CACHE.exists(), (
    f"ACAG NO₂ panel not found at {NO2_PANEL_CACHE}.\n"
    "Run ../scripts/build_acag_no2_panel.py first."
)

no2_panel = pd.read_parquet(NO2_PANEL_CACHE)
no2_panel = no2_panel[no2_panel["year"].isin(ANALYSIS_YEARS)].copy()
no2_panel = no2_panel.loc[valid_gid_mask(no2_panel["GID_2"])].copy()
no2_panel = no2_panel.dropna(subset=["no2_mean"])
no2_panel = no2_panel[no2_panel["no2_mean"] >= 0]

print(f"ACAG NO₂ panel: {len(no2_panel):,} obs | "
      f"{no2_panel['GID_2'].nunique():,} regions | "
      f"years: {sorted(no2_panel['year'].unique())}")
print(f"no2_mean (ppb): mean={no2_panel['no2_mean'].mean():.2f}, "
      f"median={no2_panel['no2_mean'].median():.2f}, "
      f"max={no2_panel['no2_mean'].max():.1f}")

ACAG NO₂ panel: 673,137 obs | 47,463 regions | years: [np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019)]
no2_mean (ppb): mean=0.96, median=0.27, max=126.8

In [8]:
# The ACAG panel is built outside the notebook by scripts/build_acag_no2_panel.py.
# This cell is just a quick diagnostic preview.
no2_panel.head()

   GID_0    GID_1       GID_2  year  no2_mean
30   AFG  AFG.1_1  AFG.1.10_1  2006  0.015511
31   AFG  AFG.1_1  AFG.1.10_1  2010  0.009289
32   AFG  AFG.1_1  AFG.1.10_1  2011  0.000725
33   AFG  AFG.1_1  AFG.1.10_1  2012  0.010424
34   AFG  AFG.1_1  AFG.1.10_1  2013  0.022686

In [9]:
assert set(ANALYSIS_YEARS).issubset(set(no2_panel["year"].unique())), (
    "ACAG panel does not cover the full analysis window."
)
print("ACAG panel covers the full 2005–2019 analysis window.")

ACAG panel covers the full 2005–2019 analysis window.

<cell_type>markdown</cell_type>## 5. Build joint panel and run Green Favoritism regressions

Merge harmonized nightlights + ACAG NO₂ + PLAD treatment for 2005–2019, then run:

$$Y_{it} = \beta \cdot \text{BirthRegion}_{it} + \alpha_i + \gamma_{ct} + \varepsilon_{it}$$

for $Y \in \{\ln(\text{lights}), \ln(\text{NO}_2)\}$ side by side.

In [10]:
# Merge nightlights + NO₂ + treatment
joint = ntl_panel.merge(no2_panel[["GID_2", "year", "no2_mean"]], on=["GID_2", "year"], how="inner")
joint = joint.merge(leader_years[["GID_2", "year", "birth_region_leader"]], on=["GID_2", "year"], how="left")
joint["birth_region_leader"] = joint["birth_region_leader"].fillna(0).astype(int)
joint = joint.merge(spell_map[["GID_0", "year", "spell_id"]], on=["GID_0", "year"], how="left")
joint["spell_id"] = joint["spell_id"].fillna(
    joint["GID_0"] + "_" + joint["year"].astype(str) + "_noleader"
).astype(str)

joint = joint.sort_values(["GID_2", "year"])
joint["brl_lag1"] = joint.groupby("GID_2")["birth_region_leader"].shift(1).fillna(0).astype(int)

joint["ln_ntl"]       = np.log(joint["ntl_mean"] + 0.01)
joint["ln_no2"]       = np.log(joint["no2_mean"] + 0.01)
joint["country_year"] = joint["GID_0"] + "_" + joint["year"].astype(str)
joint = joint.dropna(subset=["ntl_mean", "no2_mean"])
joint = joint.loc[valid_gid_mask(joint["GID_2"])].copy()

print(f"Joint panel: {len(joint):,} obs | {joint['GID_2'].nunique():,} regions | "
      f"years: {sorted(joint['year'].unique())}")
print(f"Treated obs (birth_region_leader=1): {joint['birth_region_leader'].sum()}")

Joint panel: 631,362 obs | 46,766 regions | years: [np.int64(2005), np.int64(2006), np.int64(2007), np.int64(2008), np.int64(2009), np.int64(2010), np.int64(2011), np.int64(2012), np.int64(2013), np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019)]
Treated obs (birth_region_leader=1): 1540

In [11]:
# Green Favoritism regressions: lights vs NO₂, Lag 0 and Lag 1
# FE: ADM2 region + country×year  |  Clustering: leader-period

joint_idx = joint.set_index(["GID_2", "year"])

specs    = [("Lag 0", "birth_region_leader"), ("Lag 1", "brl_lag1")]
outcomes = [("ln_ntl", "log(Nightlights)"), ("ln_no2", "log(NO₂)")]

rows = []
for lag_label, var in specs:
    for outcome_col, outcome_label in outcomes:
        model = PanelOLS.from_formula(
            f"{outcome_col} ~ {var} + EntityEffects",
            data=joint_idx,
            other_effects=joint_idx["country_year"],
            drop_absorbed=True,
        )
        res   = model.fit(cov_type="clustered", clusters=joint_idx["spell_id"])
        coef  = res.params[var]
        se    = res.std_errors[var]
        pval  = res.pvalues[var]
        stars = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.1 else ""
        rows.append({
            "Spec":    lag_label,
            "Outcome": outcome_label,
            "Coeff":   f"{coef:.4f}{stars}",
            "SE":      f"({se:.4f})",
            "p":       f"{pval:.3f}",
            "N":       f"{res.nobs:,}",
        })

results_df = pd.DataFrame(rows).set_index(["Spec", "Outcome"])
print("Green Favoritism test")
print("FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period\n")
print(results_df.to_string())
print("\nSignificance: *** p<0.01, ** p<0.05, * p<0.1")
print("\nGreen Favoritism = lights coeff > 0  AND  NO₂ coeff ≤ 0")

Green Favoritism test
FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period

                           Coeff        SE      p        N
Spec  Outcome
Lag 0 log(Nightlights)   -0.0026  (0.0091)  0.778  631,362
      log(NO₂)          0.0308**  (0.0154)  0.045  631,362
Lag 1 log(Nightlights)  -0.0137*  (0.0075)  0.067  631,362
      log(NO₂)           -0.0002  (0.0142)  0.989  631,362

Significance: *** p<0.01, ** p<0.05, * p<0.1

Green Favoritism = lights coeff > 0  AND  NO₂ coeff ≤ 0

## 6. Democracy Interaction

Hodler & Raschky's core result is strongest in autocracies. We interact `birth_region_leader` with V-Dem's electoral democracy index (`v2x_polyarchy`, 0–1).

For this specification:
- `BirthRegion` is the estimated treatment effect in a full autocracy (`democracy = 0`)
- `BirthRegion×Democracy` shows how that effect changes as democracy rises

In [12]:
VDEM_DIR = DATA / "vdem"
vdem_csv = list(VDEM_DIR.glob("*.csv")) if VDEM_DIR.exists() else []
assert vdem_csv, (
    "V-Dem CSV not found. Download the Country-Year Core CSV from "
    "https://v-dem.net/data/the-v-dem-dataset/ and place it in data/vdem/"
)

vdem = pd.read_csv(vdem_csv[0], low_memory=False)
vdem = vdem[["country_text_id", "year", "v2x_polyarchy"]].rename(
    columns={"country_text_id": "GID_0", "v2x_polyarchy": "democracy"}
)
vdem = vdem.dropna(subset=["democracy"])
vdem = vdem[vdem["year"].isin(ANALYSIS_YEARS)].copy()

joint_dem = joint.merge(vdem, on=["GID_0", "year"], how="left")
joint_dem = joint_dem.dropna(subset=["democracy"])

joint_dem["birth_x_democracy"] = joint_dem["birth_region_leader"] * joint_dem["democracy"]
joint_dem["brl_lag1_x_democracy"] = joint_dem["brl_lag1"] * joint_dem["democracy"]

print(f"V-Dem country-years: {len(vdem):,} obs | {vdem['GID_0'].nunique():,} countries")
print(f"Joint panel with democracy: {len(joint_dem):,} obs | {joint_dem['GID_2'].nunique():,} regions")

V-Dem country-years: 2,677 obs | 179 countries
Joint panel with democracy: 621,472 obs | 46,047 regions

In [13]:
# Democracy interaction: lights vs NO₂, Lag 0 and Lag 1
# FE: ADM2 region + country×year  |  Clustering: leader-period

joint_dem_idx = joint_dem.set_index(["GID_2", "year"])

specs_dem = [
    ("Lag 0", "birth_region_leader", "birth_x_democracy"),
    ("Lag 1", "brl_lag1", "brl_lag1_x_democracy"),
]
outcomes = [("ln_ntl", "log(Nightlights)"), ("ln_no2", "log(NO₂)")]

rows_dem = []
for lag_label, var, inter in specs_dem:
    for outcome_col, outcome_label in outcomes:
        model_dem = PanelOLS.from_formula(
            f"{outcome_col} ~ {var} + {inter} + EntityEffects",
            data=joint_dem_idx,
            other_effects=joint_dem_idx["country_year"],
            drop_absorbed=True,
        )
        res = model_dem.fit(cov_type="clustered", clusters=joint_dem_idx["spell_id"])

        for label, key in [("BirthRegion", var), ("BirthRegion×Democracy", inter)]:
            coef  = res.params[key]
            se    = res.std_errors[key]
            pval  = res.pvalues[key]
            stars = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.1 else ""
            rows_dem.append({
                "Spec": lag_label,
                "Outcome": outcome_label,
                "Variable": label,
                "Coeff": f"{coef:.4f}{stars}",
                "SE": f"({se:.4f})",
                "p": f"{pval:.3f}",
                "N": f"{res.nobs:,}",
            })

results_dem_df = pd.DataFrame(rows_dem).set_index(["Spec", "Outcome", "Variable"])
print("Democracy interaction")
print("Dep. vars: log(Nightlights), log(NO₂)")
print("FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period\n")
print(results_dem_df.to_string())
print("\nInterpretation: BirthRegion is the effect in a full autocracy (democracy = 0).")

Democracy interaction
Dep. vars: log(Nightlights), log(NO₂)
FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period

                                                Coeff        SE      p        N
Spec  Outcome          Variable
Lag 0 log(Nightlights) BirthRegion            -0.0032  (0.0257)  0.901  621,472
                       BirthRegion×Democracy   0.0005  (0.0402)  0.990  621,472
      log(NO₂)         BirthRegion            -0.0134  (0.0406)  0.741  621,472
                       BirthRegion×Democracy   0.0710  (0.0640)  0.268  621,472
Lag 1 log(Nightlights) BirthRegion            -0.0102  (0.0221)  0.643  621,472
                       BirthRegion×Democracy  -0.0051  (0.0337)  0.879  621,472
      log(NO₂)         BirthRegion            -0.0107  (0.0426)  0.801  621,472
                       BirthRegion×Democracy   0.0150  (0.0618)  0.808  621,472

Interpretation: BirthRegion is the effect in a full autocracy (democracy = 0).

## 7. Pollution Intensity Outcome

A direct way to test for cleaner versus dirtier growth is to use a single outcome:

$$\text{PollutionIntensity}_{it} = \ln(\text{NO}_2_{it} + 0.01) - \ln(\text{Nightlights}_{it} + 0.01)$$

A negative treatment effect means birth regions experience lower NO₂ per unit of light, consistent with cleaner growth.

In [14]:
# Pollution-intensity regressions: log(NO₂) - log(Nightlights)
# FE: ADM2 region + country×year  |  Clustering: leader-period

joint["pollution_intensity"] = joint["ln_no2"] - joint["ln_ntl"]
joint_pi = joint.set_index(["GID_2", "year"])

specs_pi = [("Lag 0", "birth_region_leader"), ("Lag 1", "brl_lag1")]
rows_pi = []
for lag_label, var in specs_pi:
    model_pi = PanelOLS.from_formula(
        f"pollution_intensity ~ {var} + EntityEffects",
        data=joint_pi,
        other_effects=joint_pi["country_year"],
        drop_absorbed=True,
    )
    res = model_pi.fit(cov_type="clustered", clusters=joint_pi["spell_id"])
    coef  = res.params[var]
    se    = res.std_errors[var]
    pval  = res.pvalues[var]
    stars = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.1 else ""
    rows_pi.append({
        "Spec": lag_label,
        "Coeff": f"{coef:.4f}{stars}",
        "SE": f"({se:.4f})",
        "p": f"{pval:.3f}",
        "N": f"{res.nobs:,}",
    })

results_pi_df = pd.DataFrame(rows_pi).set_index("Spec")
print("Pollution intensity test")
print("Dep. var: log(NO₂ + 0.01) - log(Nightlights + 0.01)")
print("FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period\n")
print(results_pi_df.to_string())
print("\nInterpretation: negative coefficients imply cleaner growth in birth regions.")

Pollution intensity test
Dep. var: log(NO₂ + 0.01) - log(Nightlights + 0.01)
FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period

         Coeff        SE      p        N
Spec
Lag 0  0.0333*  (0.0179)  0.063  631,362
Lag 1   0.0135  (0.0162)  0.404  631,362

Interpretation: negative coefficients imply cleaner growth in birth regions.

## 8. Event Study (NO₂ and Pollution Intensity)

Exploratory dynamic specification around each district's first treated year in the sample.

Event window: $k \in [-5,5]$, with $k=-1$ omitted as the reference period.

In [15]:
# Event study for NO₂ and pollution intensity
# FE: ADM2 region + country×year  |  Clustering: leader-period

if "pollution_intensity" not in joint.columns:
    joint["pollution_intensity"] = joint["ln_no2"] - joint["ln_ntl"]

joint_es = joint.copy()

# First treatment year per region in the analysis window
first_treat = (
    joint_es.loc[joint_es["birth_region_leader"] == 1]
    .groupby("GID_2")["year"]
    .min()
    .rename("first_treat_year")
)
joint_es = joint_es.merge(first_treat, on="GID_2", how="left")
joint_es["event_time"] = joint_es["year"] - joint_es["first_treat_year"]

event_ks = [k for k in range(-5, 6) if k != -1]
event_vars = []
for k in event_ks:
    name = f"ev_{'m' if k < 0 else 'p'}{abs(k)}"
    joint_es[name] = (joint_es["event_time"] == k).astype(int)
    event_vars.append((k, name))

joint_es_idx = joint_es.set_index(["GID_2", "year"])
rhs = " + ".join([v for _, v in event_vars])

es_outcomes = [
    ("ln_no2", "log(NO₂)"),
    ("pollution_intensity", "log(NO₂)-log(Nightlights)"),
]

rows_es = []
for outcome_col, outcome_label in es_outcomes:
    model_es = PanelOLS.from_formula(
        f"{outcome_col} ~ {rhs} + EntityEffects",
        data=joint_es_idx,
        other_effects=joint_es_idx["country_year"],
        drop_absorbed=True,
    )
    res = model_es.fit(cov_type="clustered", clusters=joint_es_idx["spell_id"])

    for k, var in event_vars:
        if var not in res.params.index:
            continue
        coef  = res.params[var]
        se    = res.std_errors[var]
        pval  = res.pvalues[var]
        stars = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.1 else ""
        rows_es.append({
            "Outcome": outcome_label,
            "k": k,
            "Coeff": f"{coef:.4f}{stars}",
            "SE": f"({se:.4f})",
            "p": f"{pval:.3f}",
        })

es_df = pd.DataFrame(rows_es).sort_values(["Outcome", "k"]).set_index(["Outcome", "k"])
print("Event-study coefficients (reference: k = -1)")
print("FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period\n")
print(es_df.to_string())

Event-study coefficients (reference: k = -1)
FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period

                                 Coeff        SE      p
Outcome                   k
log(NO₂)                  -5   0.0482*  (0.0275)  0.080
                          -4    0.0068  (0.0276)  0.806
                          -3    0.0308  (0.0266)  0.247
                          -2    0.0407  (0.0279)  0.145
                           0    0.0238  (0.0196)  0.226
                           1    0.0268  (0.0210)  0.202
                           2    0.0132  (0.0179)  0.462
                           3  0.0534**  (0.0238)  0.025
                           4  0.0495**  (0.0225)  0.027
                           5   -0.0085  (0.0208)  0.684
log(NO₂)-log(Nightlights) -5    0.0053  (0.0296)  0.858
                          -4   -0.0306  (0.0322)  0.341
                          -3    0.0061  (0.0301)  0.839
                          -2    0.0232  (0.0326)  0.475
                           0    0.0017  (0.0219)  0.936
                           1    0.0092  (0.0231)  0.691
                           2    0.0019  (0.0206)  0.926
                           3    0.0282  (0.0254)  0.268
                           4  0.0524**  (0.0238)  0.027
                           5   -0.0261  (0.0226)  0.248

## 9. Autocracy-Only Regressions

We restrict the sample using V-Dem `v2x_polyarchy` thresholds and estimate treatment effects for NO₂ outcomes.

In [ ]:
# Autocracy-only regressions (thresholded by democracy index)
# FE: ADM2 region + country×year  |  Clustering: leader-period

if "pollution_intensity" not in joint.columns:
    joint["pollution_intensity"] = joint["ln_no2"] - joint["ln_ntl"]

if "joint_dem" not in globals():
    VDEM_DIR = DATA / "vdem"
    vdem_csv = list(VDEM_DIR.glob("*.csv")) if VDEM_DIR.exists() else []
    assert vdem_csv, "V-Dem CSV not found in data/vdem/."
    vdem = pd.read_csv(vdem_csv[0], low_memory=False)
    vdem = vdem[["country_text_id", "year", "v2x_polyarchy"]].rename(
        columns={"country_text_id": "GID_0", "v2x_polyarchy": "democracy"}
    )
    vdem = vdem.dropna(subset=["democracy"])
    vdem = vdem[vdem["year"].isin(ANALYSIS_YEARS)].copy()
    joint_dem = joint.merge(vdem, on=["GID_0", "year"], how="left").dropna(subset=["democracy"])

autocracy_thresholds = [0.3, 0.5]
specs_auto = [("Lag 0", "birth_region_leader"), ("Lag 1", "brl_lag1")]
outcomes_auto = [
    ("ln_no2", "log(NO₂)"),
    ("pollution_intensity", "log(NO₂)-log(Nightlights)"),
]

rows_auto = []
for thr in autocracy_thresholds:
    sub = joint_dem[joint_dem["democracy"] < thr].copy()
    sub_idx = sub.set_index(["GID_2", "year"])

    for lag_label, var in specs_auto:
        for outcome_col, outcome_label in outcomes_auto:
            model = PanelOLS.from_formula(
                f"{outcome_col} ~ {var} + EntityEffects",
                data=sub_idx,
                other_effects=sub_idx["country_year"],
                drop_absorbed=True,
            )
            res = model.fit(cov_type="clustered", clusters=sub_idx["spell_id"])
            coef  = res.params[var]
            se    = res.std_errors[var]
            pval  = res.pvalues[var]
            stars = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.1 else ""
            rows_auto.append({
                "Threshold": f"democracy < {thr}",
                "Spec": lag_label,
                "Outcome": outcome_label,
                "Coeff": f"{coef:.4f}{stars}",
                "SE": f"({se:.4f})",
                "p": f"{pval:.3f}",
                "N": f"{res.nobs:,}",
            })

auto_df = pd.DataFrame(rows_auto).set_index(["Threshold", "Spec", "Outcome"])
print("Autocracy-only estimates")
print("Dep. vars: log(NO₂), pollution intensity")
print("FE: Region (ADM2) + Country×Year  |  Clustering: Leader-period\n")
print(auto_df.to_string())